version: '3.7'

networks:
  mall:
    driver: bridge

services:
  mysql-master:
    container_name: mysql-master
    image: mysql:8.0.26
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mall_db
      - MYSQL_USER=mall
      - MYSQL_PASSWORD=123456
      - TZ=Asia/Shanghai
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --require_secure_transport=OFF
    volumes:
      - ./master-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mall

  mysql-slave1:
    container_name: mysql-slave1
    image: mysql:8.0.26
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mall_db
      - MYSQL_USER=mall
      - MYSQL_PASSWORD=123456
      - TZ=Asia/Shanghai
    command: >
      --server-id=2
      --relay-log=relay-bin
      --read-only=1
      --require_secure_transport=OFF
    volumes:
      - ./slave1-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mall

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=123456
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - /usr/local/redis:/usr/local/redis
    ports:
      - "6379:6379"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    restart: always
    networks:
      - mall

  elasticsearch:
      image: elasticsearch:8.4.2
      container_name: elasticsearch
      environment:
          bootstrap.memory_lock: "true"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          discovery.type: single-node
          ingest.geoip.downloader.enabled: "false"
          TZ: Asia/Shanghai
          xpack.security.enabled: "false"
      healthcheck:
          test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"] #⼼跳检测，成功之后不再执⾏后⾯的退出
          interval: 60s #⼼跳检测间隔周期
          timeout: 10s
          retries: 3
          start_period: 60s #⾸次检测延迟时间
      ulimits:
          memlock:
              soft: -1
              hard: -1
      volumes:
          - /usr/local/elasticsearch/data:/usr/local/elasticsearch/data
          - /usr/local/elasticsearch/config/es/config:/usr/local/elasticsearch/config
      ports:
          - "9200:9200"
      restart: always
      networks:
          - mall

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP 端口
      - "15672:15672"  # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest  # 设置 RabbitMQ 默认用户名
      - RABBITMQ_DEFAULT_PASS=guest  # 设置 RabbitMQ 默认密码
    networks:
      - mall

  kibana:
    image: kibana:8.4.2
    container_name: kibana
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - mall